name = "codemanager"
type = "javascript"
compatibility_date = "2025-07-25"

kv_namespaces = [
  { binding = "ADMIN_DATA", id = "02282a84edbe421c98c057b131552347" }
]

# Uncomment and configure if you want to deploy frontend from Worker
# route = "your.domain/*"
# zone_id = "your-zone-id"


# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "CODES"
id = "f2c734b9f4bd455eafe6ecee76871ffa"

[[kv_namespaces]]
binding = "ADMIN_DATA"
id = "02282a84edbe421c98c057b131552347"
